version: "3.9"
services:
  nuxt-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app        # สำหรับ dev: sync ไฟล์จาก host
      - /app/node_modules
    environment:
      NODE_ENV: production